export const TELEGRAM_CODES = {
  HEALTH_OK: "TELEGRAM_HEALTH_OK",
  BRIDGE_DISABLED: "TELEGRAM_BRIDGE_DISABLED",
  POLLER_STOPPED: "TELEGRAM_POLLER_STOPPED",
  NOT_CONFIGURED: "TELEGRAM_NOT_CONFIGURED",
  NETWORK_ERROR: "TELEGRAM_NETWORK_ERROR",
  UNAUTHORIZED: "TELEGRAM_UNAUTHORIZED",
  SEND_FAILED: "TELEGRAM_SEND_FAILED",
  HEALTH_UNKNOWN: "TELEGRAM_HEALTH_UNKNOWN",
  HEALTH_TIMEOUT: "TELEGRAM_HEALTH_TIMEOUT",
  HEALTH_UNAVAILABLE: "TELEGRAM_HEALTH_UNAVAILABLE",
  HEALTH_UNREACHABLE: "TELEGRAM_HEALTH_UNREACHABLE",
} as const;

export type TelegramCode = (typeof TELEGRAM_CODES)[keyof typeof TELEGRAM_CODES] | string;
