from __future__ import annotations

# Success / informational codes
TELEGRAM_HEALTH_OK = "TELEGRAM_HEALTH_OK"
TELEGRAM_BRIDGE_DISABLED = "TELEGRAM_BRIDGE_DISABLED"
TELEGRAM_POLLER_STOPPED = "TELEGRAM_POLLER_STOPPED"
TELEGRAM_POLLER_STARTED = "TELEGRAM_POLLER_STARTED"
TELEGRAM_POLL_OK = "TELEGRAM_POLL_OK"
TELEGRAM_POLL_PARTIAL = "TELEGRAM_POLL_PARTIAL"
TELEGRAM_SENT = "TELEGRAM_SENT"

# Error codes
TELEGRAM_NOT_CONFIGURED = "TELEGRAM_NOT_CONFIGURED"
TELEGRAM_INVALID_AGENT = "TELEGRAM_INVALID_AGENT"
TELEGRAM_SEND_FAILED = "TELEGRAM_SEND_FAILED"
TELEGRAM_BAD_REQUEST = "TELEGRAM_BAD_REQUEST"
TELEGRAM_FORBIDDEN = "TELEGRAM_FORBIDDEN"
TELEGRAM_RATE_LIMITED = "TELEGRAM_RATE_LIMITED"
TELEGRAM_UNAUTHORIZED = "TELEGRAM_UNAUTHORIZED"
TELEGRAM_NETWORK_ERROR = "TELEGRAM_NETWORK_ERROR"
TELEGRAM_UNKNOWN_ERROR = "TELEGRAM_UNKNOWN_ERROR"
TELEGRAM_POLL_CONFLICT = "TELEGRAM_POLL_CONFLICT"
TELEGRAM_POLL_FAILED = "TELEGRAM_POLL_FAILED"
